[project]
name = "src"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.6"
dependencies = [
    "beir>=2.1.0",
    "numpy>=2.2.5",
    "openai>=1.78.1",
    "torch>=2.7.0",
    "vec2text>=0.0.13",
    "wandb>=0.19.11",
]
